services:
  # Managed PostgreSQL Database
  - name: postgres-db
    type: pserv
    plan: free # Or choose a paid plan
    postgres:
      version: "13"

  # Managed Redis Instance
  - name: redis-cache
    type: pserv
    plan: free # Or choose a paid plan
    redis:
      version: "6.2"

  # Django Web Service
  - name: web
    type: web
    plan: free # Or choose a paid plan
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: pserv
          name: redis-cache
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will generate a secure secret key
      - key: PYTHONUNBUFFERED
        value: 1
    autoDeploy: true

  # Celery Background Worker
  - name: celery-worker
    type: worker
    plan: free # Or choose a paid plan
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: celery -A memetrends worker -l info
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: pserv
          name: redis-cache
          property: connectionString
      - key: SECRET_KEY
        fromService:
          type: web
          name: web
          envVarKey: SECRET_KEY # Use the same secret key as the web service
      - key: PYTHONUNBUFFERED
        value: 1
