services:
  # Managed PostgreSQL Database
  - name: postgres-db
    type: pserv
    plan: free
    postgresVersion: 13

  # Managed Redis Instance
  - name: redis-cache
    type: pserv
    plan: free
    redisVersion: "6.2"

  # Django Web Service
  - name: web
    type: web
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: pserv
          name: redis-cache
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: 1

  # Celery Background Worker
  - name: celery-worker
    type: worker
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: celery -A memetrends worker -l info
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: pserv
          name: redis-cache
          property: connectionString
      - key: SECRET_KEY
        fromService:
          type: web
          name: web
          envVarKey: SECRET_KEY
      - key: PYTHONUNBUFFERED
        value: 1