# Generated by Django 5.2.6 on 2025-09-12 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reddit", "Reddit"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("media", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("posted_at", models.DateTimeField()),
                ("engagement_score", models.IntegerField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
