# Generated by Django 5.2.6 on 2025-09-15 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meme",
            name="engagement_score",
        ),
        migrations.AddField(
            model_name="meme",
            name="comments",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="meme",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="meme",
            name="shares",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="meme",
            name="trending_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name="meme",
            index=models.Index(
                fields=["platform", "posted_at"], name="memes_meme_platfor_629891_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meme",
            index=models.Index(
                fields=["-trending_score"], name="memes_meme_trendin_411049_idx"
            ),
        ),
    ]
