# Generated by Django 5.2.6 on 2025-09-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memes", "0002_remove_meme_engagement_score_meme_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meme",
            name="comments",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="meme",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="meme",
            name="shares",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
